# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dad9ac00aebd96d5dca99468bba270917588c270486e944000fe835dfed6e05a7c4fafbc09e90faf3f8dba243cc82b0f3f79d82650967a44898ef03b167f56c1

test:
  secret_key_base: 6e7d7c808af12232264c94aa3cb7a2f798d3f1673bb8e4a99011eff202adb3c9738d3d21d68e2aa03701371406668d6c729d4c2de062919f08ef73a9bd4b3c64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
