# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6d7222d9b390d2fac8bd08c59c7763610f43f5a2d7d185afed5be9ba0f90cbb04550b5c5501f184315269b5c82934832de374ae62a453ab015c53d5a0995628

test:
  secret_key_base: 908dfdeebf5ac304eb448d23ec5390e9a1e825a36d0f914b27c81d60c8323c5c1ebcd7a3ab0a9c47d8b57cd865cc2c5ae3ac92c8e1ad7d5ae599081cd60ca0bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
